# Use tinnova/tinnova123 user/password credentials
version: '3.1'

services:   

  db:
    image: postgres:alpine3.14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tinnova
      POSTGRES_PASSWORD: tinnova123

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
