# Use tinnova/tinnova@123 user/password credentials
version: '3.1'

services:   

  db:
    image: postgres:alpine3.14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tinnova
      POSTGRES_PASSWORD: tinnova@123